name: Node.js Build
on:
  push:
    branches:
      - feat/build-nodejs
    # paths:
    #   - nodejs/**
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependency & run test
        run: |
          cd nodejs
          npm install
          npm test
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: "actions/checkout@v3"
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - name: Deploy to cloud run
        run: "gcloud run deploy sby-hacktoberfest-demo --region asia-southeast2-b --source . --entrypoint server.js"
